version: "3.5"
services:
  wireguard:
    image: eftechcombr/wireguard:dev
    build: . 
    cap_add:
      - NET_ADMIN
    sysctls:
     - net.ipv4.ip_forward=1
    volumes: 
      - /dev/net/tun:/dev/net/tun
      - ./etc:/etc/wireguard:rw 
    ports: 
      - "51820:51820/UDP"
      - "8080:8080"

